#!/bin/bash

PROJECT_ROOT=$(pwd)
export PROJECT_ROOT

ANDROID_KEY_PROPERTIES=$PROJECT_ROOT/android/key.properties
export ANDROID_KEY_PROPERTIES

SECURE_FILES=$PROJECT_ROOT/.secure_files
export SECURE_FILES

ARTIFACTS=$PROJECT_ROOT/artifacts
export ARTIFACTS

APK_FLUTTER_SYMBOLS=$ARTIFACTS/android/symbols/apk
export APK_FLUTTER_SYMBOLS

AAB_FLUTTER_SYMBOLS=$ARTIFACTS/android/symbols/aab
export AAB_FLUTTER_SYMBOLS

IPA_FLUTTER_SYMBOLS=$ARTIFACTS/ios/symbols
export IPA_FLUTTER_SYMBOLS

PROJECT_RUBY_VERSION="3.3.0"
export PROJECT_RUBY_VERSION

PROJECT_FLUTTER_VERSION="3.22.2"
export PROJECT_FLUTTER_VERSION

EXPORT_OPTIONS_PLIST=$PROJECT_ROOT/ios/Runner/ExportOptions.plist
export EXPORT_OPTIONS_PLIST

TEMP_KEYCHAIN="temporary/example-signing.keychain-db"
export TEMP_KEYCHAIN

TEMP_KEYCHAIN_PASSWORD="example-signing"
export TEMP_KEYCHAIN_PASSWORD

APP_CONFIG=$PROJECT_ROOT/configs/app_config.json
export APP_CONFIG

CONFIG=$SECURE_FILES/config.yml
export CONFIG

PROD_CONFIG=$SECURE_FILES/prod_config.yml
export PROD_CONFIG

DEV_CONFIG=$SECURE_FILES/dev_config.yml
export DEV_CONFIG